### ISSUE TITLE
es-theme-knulli updater bug

### ISSUE THREAD

**Issue by symbuzzer** [zarquon-42/knulli-patch-installer#7]
![5852939757930267711](https://github.com/user-attachments/assets/63905b92-aeaa-4d5f-b90d-abefede37068)

**Comment by zarquon-42** [comment]
@symbuzzer can you turn on debugging mode (press x) and send the log located at /userdata/systems/logs/patch-installer.log

**Comment by zarquon-42** [comment]
OK, I found the issue.  It was in the version check command in the patch definition.  This has been updated and should fix the problem.  This will require reloading the patch definitions by pressing "Y"

**Comment by zarquon-42** [comment]
OK, I found the issue. It was in the version check command in the patch definition. This has been updated and should fix the problem. This will require reloading the patch definitions by pressing "Y"
