### ISSUE TITLE
es-theme-knulli version string changed

### ISSUE THREAD

**Issue by symbuzzer** [zarquon-42/knulli-patch-installer#9]
you should grab it from <v.themeVersion>2.1.0</v.themeVersion>  in theme.xml

**Comment by zarquon-42** [comment]
This will have to check both the old and new formats otherwise unexpected behaviour would happen going from 1.x.x to 2.x.x

Should be able to modify the grep / sed statements to account for both.

**Comment by zarquon-42** [comment]
Fixed with this commit: https://github.com/zarquon-42/knulli-patch-installer/commit/59ca5d3a28b5efd7da8893721dd26f64e613ff90
